"""product discount price and brand

Revision ID: afd647a4bd3b
Revises: eea10e6e9d4d
Create Date: 2023-09-04 13:30:30.666345

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "afd647a4bd3b"
down_revision = "eea10e6e9d4d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("discount_price", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "products",
        sa.Column(
            "brand_translations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "brand_translations")
    op.drop_column("products", "discount_price")
    # ### end Alembic commands ###
