"""Add muscle groups

Revision ID: 096487b299b1
Revises: 25a8d71a0071
Create Date: 2023-05-26 13:32:56.893625

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "096487b299b1"
down_revision = "25a8d71a0071"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "muscle_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "name_translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("image_path", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("muscle_groups")
    # ### end Alembic commands ###
