"""Add body part

Revision ID: 0556029e25b1
Revises: bc06b7d7b17b
Create Date: 2023-06-03 12:22:42.121972

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0556029e25b1"
down_revision = "bc06b7d7b17b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    body_part = postgresql.ENUM("upper_body", "lower_body", "core", name="body_type")
    body_part.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "muscle_groups",
        sa.Column(
            "body_part",
            body_part,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    body_part = postgresql.ENUM(name="body_type")
    body_part.drop(op.get_bind())
    op.drop_column("muscle_groups", "body_part")
    # ### end Alembic commands ###
