"""Equipment translations

Revision ID: 25a8d71a0071
Revises: c617910edac2
Create Date: 2023-05-21 15:21:38.147537

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "25a8d71a0071"
down_revision = "c617910edac2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "equipment",
        sa.Column(
            "name_translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    op.drop_index("ix_equipment_name", table_name="equipment")
    op.drop_column("equipment", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "equipment",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_index("ix_equipment_name", "equipment", ["name"], unique=False)
    op.drop_column("equipment", "name_translations")
    # ### end Alembic commands ###
