"""saved fitness plans

Revision ID: 8d72c23f9f27
Revises: cbe81d8d88aa
Create Date: 2023-08-11 10:20:15.168942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d72c23f9f27'
down_revision = 'cbe81d8d88aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_saved_fitness_plans',
    sa.Column('fitness_plan_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fitness_plan_id'], ['fitness_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fitness_plan_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_saved_fitness_plans')
    # ### end Alembic commands ###
