"""rename break field

Revision ID: 62b9970ed943
Revises: a0bfeef428f8
Create Date: 2023-07-19 09:27:50.024713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b9970ed943'
down_revision = 'a0bfeef428f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercise_sets', sa.Column('break', sa.Integer(), nullable=True))
    op.drop_column('workout_exercise_sets', 'break_')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercise_sets', sa.Column('break_', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('workout_exercise_sets', 'break')
    # ### end Alembic commands ###
