"""fitness plan weeks

Revision ID: 941c1fe63589
Revises: adafe3044987
Create Date: 2023-07-25 10:55:12.918031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941c1fe63589'
down_revision = 'adafe3044987'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitness_plan_weeks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fitness_plan_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fitness_plan_id'], ['fitness_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fitness_plan_id', 'order', deferrable='True', initially='DEFERRED', name='fitness_plan_weeks_unique_order')
    )
    op.create_index(op.f('ix_fitness_plan_weeks_fitness_plan_id'), 'fitness_plan_weeks', ['fitness_plan_id'], unique=False)
    op.create_table('fitness_plan_week_workouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fitness_plan_week_id', sa.Uuid(), nullable=False),
    sa.Column('workout_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fitness_plan_week_id'], ['fitness_plan_weeks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fitness_plan_week_id', 'order', deferrable='True', initially='DEFERRED', name='fitness_plan_week_workouts_unique_order')
    )
    op.create_index(op.f('ix_fitness_plan_week_workouts_fitness_plan_week_id'), 'fitness_plan_week_workouts', ['fitness_plan_week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fitness_plan_week_workouts_fitness_plan_week_id'), table_name='fitness_plan_week_workouts')
    op.drop_table('fitness_plan_week_workouts')
    op.drop_index(op.f('ix_fitness_plan_weeks_fitness_plan_id'), table_name='fitness_plan_weeks')
    op.drop_table('fitness_plan_weeks')
    # ### end Alembic commands ###
