"""Add admins

Revision ID: 50e1e4c5bd8c
Revises: 7aca75782d4b
Create Date: 2023-04-30 12:32:26.100610

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "50e1e4c5bd8c"
down_revision = "7aca75782d4b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("activation_token", sa.String(), nullable=True),
        sa.Column("activated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activation_token"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "admin_authentication_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("admin_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["admin_id"], ["admins.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        op.f("ix_admin_authentication_tokens_admin_id"),
        "admin_authentication_tokens",
        ["admin_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_authentication_tokens_user_id"),
        "user_authentication_tokens",
        ["user_id"],
        unique=False,
    )
    op.alter_column("users", "height", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "height", existing_type=sa.INTEGER(), nullable=False)
    op.drop_index(
        op.f("ix_user_authentication_tokens_user_id"),
        table_name="user_authentication_tokens",
    )
    op.drop_index(
        op.f("ix_admin_authentication_tokens_admin_id"),
        table_name="admin_authentication_tokens",
    )
    op.drop_table("admin_authentication_tokens")
    op.drop_table("admins")
    # ### end Alembic commands ###
