"""delete workout exercises

Revision ID: 0396da6e4a27
Revises: a2a3f902512c
Create Date: 2023-07-25 10:20:16.349517

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0396da6e4a27"
down_revision = "a2a3f902512c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "workout_exercises_workout_id_fkey", "workout_exercises", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "workout_exercises",
        "workouts",
        ["workout_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workout_exercises", type_="foreignkey")
    op.create_foreign_key(
        "workout_exercises_workout_id_fkey",
        "workout_exercises",
        "workouts",
        ["workout_id"],
        ["id"],
    )
    # ### end Alembic commands ###
