"""user workouts

Revision ID: cbe81d8d88aa
Revises: 941c1fe63589
Create Date: 2023-07-31 11:44:42.132029

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "cbe81d8d88aa"
down_revision = "941c1fe63589"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_fitness_plans_participations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("fitness_plan_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fitness_plan_id"],
            ["fitness_plans.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_fitness_plans_participations_fitness_plan_id"),
        "user_fitness_plans_participations",
        ["fitness_plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_fitness_plans_participations_user_id"),
        "user_fitness_plans_participations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_workouts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workout_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("fitness_plan_participation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fitness_plan_participation_id"],
            ["user_fitness_plans_participations.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(
        "ix_user_completed_workouts_user_id", table_name="user_completed_workouts"
    )
    op.drop_index(
        "ix_user_completed_workouts_workout_id", table_name="user_completed_workouts"
    )
    op.drop_table("user_completed_workouts")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_completed_workouts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("workout_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_completed_workouts_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
            name="user_completed_workouts_workout_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="user_completed_workouts_pkey"),
    )
    op.create_index(
        "ix_user_completed_workouts_workout_id",
        "user_completed_workouts",
        ["workout_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_completed_workouts_user_id",
        "user_completed_workouts",
        ["user_id"],
        unique=False,
    )
    op.drop_table("user_workouts")
    op.drop_index(
        op.f("ix_user_fitness_plans_participations_user_id"),
        table_name="user_fitness_plans_participations",
    )
    op.drop_index(
        op.f("ix_user_fitness_plans_participations_fitness_plan_id"),
        table_name="user_fitness_plans_participations",
    )
    op.drop_table("user_fitness_plans_participations")
    # ### end Alembic commands ###
