"""Saved workouts

Revision ID: 4ec46f211fb3
Revises: 943e51557d07
Create Date: 2023-06-27 12:55:51.825143

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4ec46f211fb3"
down_revision = "943e51557d07"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_saved_workouts",
        sa.Column("workout_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workout_id", "user_id"),
    )
    op.create_index(
        op.f("ix_workouts_fitness_coach_id"),
        "workouts",
        ["fitness_coach_id"],
        unique=False,
    )
    op.drop_constraint("workouts_order_id_fkey", "workouts", type_="foreignkey")
    op.create_foreign_key(
        None, "workouts", "orders", ["order_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workouts", type_="foreignkey")
    op.create_foreign_key(
        "workouts_order_id_fkey", "workouts", "orders", ["order_id"], ["id"]
    )
    op.drop_index(op.f("ix_workouts_fitness_coach_id"), table_name="workouts")
    op.drop_table("user_saved_workouts")
    # ### end Alembic commands ###
