"""workout age

Revision ID: 8dd3f129e77c
Revises: f5c613c7015e
Create Date: 2023-07-07 10:42:12.655320

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8dd3f129e77c"
down_revision = "f5c613c7015e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workouts", sa.Column("min_age", sa.Integer(), nullable=True))
    op.add_column("workouts", sa.Column("max_age", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workouts", "max_age")
    op.drop_column("workouts", "min_age")
    # ### end Alembic commands ###
