"""pr observations

Revision ID: 4c64aba66100
Revises: 8d72c23f9f27
Create Date: 2023-08-21 14:47:35.427624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c64aba66100'
down_revision = '8d72c23f9f27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_observations_user_id'), 'pr_observations', ['user_id', 'exercise_id'], unique=False)
    op.drop_index('ix_user_fitness_plans_participations_user_id', table_name='user_fitness_plans_participations')
    op.create_index(op.f('ix_user_fitness_plans_participations_user_id'), 'user_fitness_plans_participations', ['user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_fitness_plans_participations_user_id'), table_name='user_fitness_plans_participations', postgresql_where=sa.text('is_active = true'))
    op.create_index('ix_user_fitness_plans_participations_user_id', 'user_fitness_plans_participations', ['user_id'], unique=False)
    op.drop_index(op.f('ix_pr_observations_user_id'), table_name='pr_observations')
    op.drop_table('pr_observations')
    # ### end Alembic commands ###
