"""fitness coach is released

Revision ID: eea10e6e9d4d
Revises: 61580ad3edde
Create Date: 2023-09-01 12:26:54.411984

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "eea10e6e9d4d"
down_revision = "61580ad3edde"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fitness_coaches",
        sa.Column(
            "is_released", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fitness_coaches", "is_released")
    # ### end Alembic commands ###
