"""workout sex and focus

Revision ID: f5c613c7015e
Revises: 4ec46f211fb3
Create Date: 2023-07-03 12:44:18.615551

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "f5c613c7015e"
down_revision = "4ec46f211fb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workouts",
        sa.Column(
            "focus",
            postgresql.ENUM(name="focus", create_type=False),
            nullable=True,
        ),
    )
    op.add_column(
        "workouts",
        sa.Column(
            "target_sex", postgresql.ENUM(name="sex", create_type=False), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workouts", "target_sex")
    op.drop_column("workouts", "focus")
    # ### end Alembic commands ###
