"""delete weight field

Revision ID: adafe3044987
Revises: 0396da6e4a27
Create Date: 2023-07-25 10:34:03.699608

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "adafe3044987"
down_revision = "0396da6e4a27"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "weight")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("weight", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
