"""Add country to users

Revision ID: 1ab298af8b7c
Revises: 925f9627cc32
Create Date: 2023-05-06 11:58:26.822827

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1ab298af8b7c"
down_revision = "925f9627cc32"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("country_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "users", "countries", ["country_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "country_id")
    # ### end Alembic commands ###
