"""completed workouts

Revision ID: 8a0a7d72b04d
Revises: 8dd3f129e77c
Create Date: 2023-07-12 10:54:08.374171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0a7d72b04d'
down_revision = '8dd3f129e77c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_completed_workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_completed_workouts_user_id'), 'user_completed_workouts', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_completed_workouts_workout_id'), 'user_completed_workouts', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_completed_workouts_workout_id'), table_name='user_completed_workouts')
    op.drop_index(op.f('ix_user_completed_workouts_user_id'), table_name='user_completed_workouts')
    op.drop_table('user_completed_workouts')
    # ### end Alembic commands ###
